### ISSUE TITLE
Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by kart-manohar** [singer-io/tap-impact#15]
Hi!

I am running into issues with my impact integration in stitch. I have been getting a series of errors since I integrated with the most recent one being -''Can't convert 'NoneType' object to str implicitly'.

What would be the best way to resolve this issue and ensure smooth ingestion going forward?  thanks!

**Comment by toandm** [comment]
Hi I have this same issue. Anyone been working on this?

**Comment by toandm** [comment]
Hi @jeffhuth-bytecode @asaf-erlich I also have this issue and our client is complaining about this. Any idea how to fix it? Here is the log if you need
```
2022-09-22 05:31:13,392Z    tap - INFO START Sync for Stream: action_updates, parent_stream: campaigns, parent_id: 11111
2022-09-22 05:31:13,392Z    tap - CRITICAL Can't convert 'NoneType' object to str implicitly
2022-09-22 05:31:13,392Z    tap - Traceback (most recent call last):
2022-09-22 05:31:13,392Z    tap -   File "tap-env/bin/tap-impact", line 33, in <module>
2022-09-22 05:31:13,392Z    tap -     sys.exit(load_entry_point('tap-impact==1.0.0', 'console_scripts', 'tap-impact')())
2022-09-22 05:31:13,392Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2022-09-22 05:31:13,392Z    tap -     return fnc(*args, **kwargs)
2022-09-22 05:31:13,392Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_impact/__init__.py", line 50, in main
2022-09-22 05:31:13,393Z    tap -     state=state)
2022-09-22 05:31:13,393Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_impact/sync.py", line 421, in sync
2022-09-22 05:31:13,393Z    tap -     selected_streams=selected_streams)
2022-09-22 05:31:13,393Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_impact/sync.py", line 315, in sync_endpoint
2022-09-22 05:31:13,393Z    tap -     '<model_id>', model_id)
2022-09-22 05:31:13,393Z    tap - TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by jeffhuth-windriver** [comment]
You will need to contact Impact Support to get your organization's unique `model_id` and include this as a parameter in your `config.json` file.

**Comment by toandm** [comment]
Thanks @jeffhuth-windriver , I found the model_id, input it in and it worked! However, there are issues related to 2 more tables that I have reported in issue #19
